defaults:
  - peft: inactive
  - optimizer: adam
  - scheduler: inactive
  - quantization: inactive

seed: 42
epochs: 2
# Training scheme
strategy: GPLA
K: 5
# Preference Score
preference_score:
  checkpoint: null
# Loss
cpo:
  beta: 0.1
  label_smoothing: 0.0
optimizer_step_freq: 2
batch_size: 2
# Early Stopping
stop_train_after: 2
stop_val_after: 2
stop_test_after: 2

device: gpu
autocast: True
